In [1]:
import numpy as np
import pandas as pd
train_df=pd.read_csv("training-images.csv",header=None)
train_df.rename(columns={ train_df.columns[784]: "Label" }, inplace = True)
train_df

0    1    2    3    4    5    6    7    8    9  ...  775  776  777  \
0    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
1    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
2    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
3    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
4    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
445  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
446  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
447  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
448  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
449  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   

     778  779  780  781  782  783  Label  
0    255  255  255  255  255  255      0  
1    255  255  255  255  255  255      0  
2    255  255  255  255  255  255      0  
3    255  255  255  255  255  255      0  
4    255  255  255  255  255  255      0  
..   ...  ...  ...  ...  ...  ...    ...  
445  255  255  255  255  255  255      3  
446  255  255  255  255  255  255      3  
447  255  255  255  255  255  255      3  
448  255  255  255  255  255  255      3  
449  255  255  255  255  255  255      3  

[450 rows x 785 columns]

In [2]:
test_df=pd.read_csv("test-images.csv",header=None)
test_df.rename(columns={ test_df.columns[784]: "Label" }, inplace = True)
test_df

0    1    2    3    4    5    6    7    8    9  ...  775  776  777  \
0    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
1    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
2    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
3    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
4    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
199  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
200  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
201  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
202  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
203  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   

     778  779  780  781  782  783  Label  
0    255  255  255  255  255  255      0  
1    255  255  255  255  255  255      0  
2    255  255  255  255  255  255      0  
3    255  255  255  255  255  255      0  
4    255  255  255  255  255  255      0  
..   ...  ...  ...  ...  ...  ...    ...  
199  255  255  255  255  255  255      3  
200  255  255  255  255  255  255      3  
201  255  255  255  255  255  255      3  
202  255  255  255  255  255  255      3  
203  255  255  255  255  255  255      3  

[204 rows x 785 columns]

In [3]:
X_train=train_df.sample(frac=1, random_state=5).iloc[:,:-1]
y_train=train_df.sample(frac=1, random_state=5).iloc[:,[-1]]

In [4]:
X_test=test_df.sample(frac=1, random_state=5).iloc[:,:-1]
y_test=test_df.sample(frac=1, random_state=5).iloc[:,[-1]]

In [5]:
X_train

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  \
286  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
40   255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
333  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
262  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
222  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
400  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
118  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
189  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
206  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
355  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   

     777  778  779  780  781  782  783  
286  255  255  255  255  255  255  255  
40   255  255  255  255  255  255  255  
333  255  255  255  255  255  255  255  
262  255  255  255  255  255  255  255  
222  255  255  255  255  255  255  255  
..   ...  ...  ...  ...  ...  ...  ...  
400  255  255  255  255  255  255  255  
118  255  255  255  255  255  255  255  
189  255  255  255  255  255  255  255  
206  255  255  255  255  255  255  255  
355  255  255  255  255  255  255  255  

[450 rows x 784 columns]

In [6]:
y_train

Label
286      2
40       0
333      2
262      2
222      1
..     ...
400      3
118      0
189      1
206      1
355      3

[450 rows x 1 columns]

In [7]:
X_test

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  \
153  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
21   255  255  255  255  255  255  255  255  255  255  ...    0  255  255   
202  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
48   255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
34   255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
73   255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
144  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
118  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
189  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
99   255  255  255  255  255  255  255  255  255  255  ...  255  255  255   

     777  778  779  780  781  782  783  
153  255  255  255  255  255  255  255  
21   255  255  255  255  255  255  255  
202  255  255  255  255  255  255  255  
48   255  255  255  255  255  255  255  
34   255  255  255  255  255  255  255  
..   ...  ...  ...  ...  ...  ...  ...  
73   255  255  255  255  255  255  255  
144  255  255  255  255  255  255  255  
118  255  255  255  255  255  255  255  
189  255  255  255  255  255  255  255  
99   255  255  255  255  255  255  255  

[204 rows x 784 columns]

In [8]:
y_test

Label
153      2
21       0
202      3
48       0
34       0
..     ...
73       1
144      2
118      2
189      3
99       1

[204 rows x 1 columns]

In [9]:
X = X_train.iloc[:,:]
y = y_train['Label']
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [10]:
neigh.classes_

array([0, 1, 2, 3], dtype=int64)

In [11]:
neigh.predict_proba(X_test.iloc[[0]])

array([[0.        , 0.66666667, 0.        , 0.33333333]])

In [12]:
neigh.predict(X_test.iloc[[0]])

array([1], dtype=int64)

In [13]:
neigh.predict_proba(X_test.iloc[:,:])

array([[0.        , 0.66666667, 0.        , 0.33333333],
       [0.33333333, 0.33333333, 0.        , 0.33333333],
       [0.        , 0.        , 0.        , 1.        ],
       [0.66666667, 0.        , 0.        , 0.33333333],
       [0.33333333, 0.33333333, 0.        , 0.33333333],
       [0.        , 0.        , 0.        , 1.        ],
       [0.66666667, 0.        , 0.        , 0.33333333],
       [0.        , 0.33333333, 0.        , 0.66666667],
       [0.        , 0.        , 0.        , 1.        ],
       [0.        , 0.        , 0.33333333, 0.66666667],
       [0.        , 0.33333333, 0.        , 0.66666667],
       [0.        , 0.        , 0.        , 1.        ],
       [0.        , 1.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ],
       [0.        , 0.        , 0.        , 1.        ],
       [0.        , 0.        , 0.        , 1.        ],
       [0.        , 1.        , 0.        , 0.        ],
       [0.        , 0.66666667,

In [14]:
neigh.predict(X_test.iloc[:,:])

array([1, 0, 3, 0, 0, 3, 0, 3, 3, 3, 3, 3, 1, 3, 3, 3, 1, 1, 1, 1, 2, 1,
       0, 1, 1, 1, 0, 1, 3, 1, 3, 1, 3, 3, 0, 3, 1, 0, 3, 1, 0, 0, 3, 1,
       3, 1, 1, 3, 1, 3, 1, 1, 1, 0, 0, 0, 3, 1, 3, 3, 3, 3, 2, 0, 1, 1,
       1, 3, 1, 3, 0, 1, 3, 3, 0, 1, 1, 1, 1, 2, 3, 1, 0, 1, 0, 3, 3, 3,
       0, 1, 0, 1, 1, 3, 1, 3, 3, 1, 1, 2, 3, 3, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 2, 2, 1, 1, 1, 1, 0, 3, 3, 1, 3, 0, 3, 1, 3, 1, 3, 1, 1,
       3, 1, 0, 1, 3, 3, 0, 3, 0, 3, 0, 1, 0, 3, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 3, 0, 3, 3, 0, 1, 0, 0, 3, 1, 3, 2, 2, 0, 1, 0, 1, 2,
       0, 0, 0, 1, 1, 3, 1, 1, 0, 3, 1, 0, 0, 1, 3, 1, 1, 0, 3, 1, 3, 3,
       0, 1, 3, 2, 3, 1], dtype=int64)

In [15]:
neigh.score(X_test.iloc[:,:], y_test['Label'])

0.7352941176470589