In [1]:
import numpy as np
import pandas as pd
train_df=pd.read_csv("training-images.csv",header=None)
train_df.rename(columns={ train_df.columns[784]: "Label" }, inplace = True)
train_df

0    1    2    3    4    5    6    7    8    9  ...  775  776  777  \
0    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
1    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
2    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
3    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
4    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
445  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
446  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
447  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
448  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
449  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   

     778  779  780  781  782  783  Label  
0    255  255  255  255  255  255      0  
1    255  255  255  255  255  255      0  
2    255  255  255  255  255  255      0  
3    255  255  255  255  255  255      0  
4    255  255  255  255  255  255      0  
..   ...  ...  ...  ...  ...  ...    ...  
445  255  255  255  255  255  255      3  
446  255  255  255  255  255  255      3  
447  255  255  255  255  255  255      3  
448  255  255  255  255  255  255      3  
449  255  255  255  255  255  255      3  

[450 rows x 785 columns]

In [2]:
test_df=pd.read_csv("test-images.csv",header=None)
test_df.rename(columns={ test_df.columns[784]: "Label" }, inplace = True)
test_df

0    1    2    3    4    5    6    7    8    9  ...  775  776  777  \
0    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
1    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
2    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
3    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
4    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
199  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
200  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
201  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
202  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
203  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   

     778  779  780  781  782  783  Label  
0    255  255  255  255  255  255      0  
1    255  255  255  255  255  255      0  
2    255  255  255  255  255  255      0  
3    255  255  255  255  255  255      0  
4    255  255  255  255  255  255      0  
..   ...  ...  ...  ...  ...  ...    ...  
199  255  255  255  255  255  255      3  
200  255  255  255  255  255  255      3  
201  255  255  255  255  255  255      3  
202  255  255  255  255  255  255      3  
203  255  255  255  255  255  255      3  

[204 rows x 785 columns]

In [3]:
X_train=train_df.sample(frac=1, random_state=5).iloc[:,:-1]
y_train=train_df.sample(frac=1, random_state=5).iloc[:,[-1]]

In [4]:
X_test=test_df.sample(frac=1, random_state=5).iloc[:,:-1]
y_test=test_df.sample(frac=1, random_state=5).iloc[:,[-1]]

In [5]:
X_train

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  \
286  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
40   255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
333  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
262  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
222  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
400  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
118  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
189  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
206  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
355  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   

     777  778  779  780  781  782  783  
286  255  255  255  255  255  255  255  
40   255  255  255  255  255  255  255  
333  255  255  255  255  255  255  255  
262  255  255  255  255  255  255  255  
222  255  255  255  255  255  255  255  
..   ...  ...  ...  ...  ...  ...  ...  
400  255  255  255  255  255  255  255  
118  255  255  255  255  255  255  255  
189  255  255  255  255  255  255  255  
206  255  255  255  255  255  255  255  
355  255  255  255  255  255  255  255  

[450 rows x 784 columns]

In [6]:
y_train

Label
286      2
40       0
333      2
262      2
222      1
..     ...
400      3
118      0
189      1
206      1
355      3

[450 rows x 1 columns]

In [7]:
X_test

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  \
153  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
21   255  255  255  255  255  255  255  255  255  255  ...    0  255  255   
202  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
48   255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
34   255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
73   255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
144  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
118  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
189  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
99   255  255  255  255  255  255  255  255  255  255  ...  255  255  255   

     777  778  779  780  781  782  783  
153  255  255  255  255  255  255  255  
21   255  255  255  255  255  255  255  
202  255  255  255  255  255  255  255  
48   255  255  255  255  255  255  255  
34   255  255  255  255  255  255  255  
..   ...  ...  ...  ...  ...  ...  ...  
73   255  255  255  255  255  255  255  
144  255  255  255  255  255  255  255  
118  255  255  255  255  255  255  255  
189  255  255  255  255  255  255  255  
99   255  255  255  255  255  255  255  

[204 rows x 784 columns]

In [8]:
y_test

Label
153      2
21       0
202      3
48       0
34       0
..     ...
73       1
144      2
118      2
189      3
99       1

[204 rows x 1 columns]

In [9]:
import numpy as np
X = np.array(X_train.values)
y = np.array(y_train.values)
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB() 
#clf = GaussianNB(priors=[0.5, 0.5]) #here priors are set to 50%, remove for improving accuracy
#priors is the distributioon of output classes in the data
clf.fit(X, y)

C:\Users\soham\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [10]:
# first row of our test data
a=np.array(X_test.values)[0]
a

array([255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255,   0,   0,   0,   0, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255,   0,   0, 255, 255, 255,   0,   0, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255,   0, 255, 255, 255, 255, 255,   0,   0, 255,
       255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255, 255, 255, 255,   0, 255, 255, 255, 255,   

In [11]:
#to check the prediction of a single row
#checking the prediction of our first row in test data
predictSingle=clf.predict([a]) #we enclose 'a' in '[]' because we are supposed to pass a 2-D array to the .predict() function
#so we take our first row, which is a 1-D array and convert it to a 2-D array by enclosing it in '[]' 
print(predictSingle)
print(type(predictSingle))

[2]
<class 'numpy.ndarray'>


In [12]:
clf.classes_

array([0, 1, 2, 3], dtype=int64)

In [13]:
predlist=clf.predict(np.array(X_test.values))
print(predlist)
print(type(predlist))

[2 0 3 0 0 3 0 0 0 2 1 0 2 3 3 2 1 1 1 1 1 1 0 2 1 0 0 0 3 1 3 1 3 3 0 3 1
 0 3 2 0 0 3 1 3 2 2 3 1 2 1 1 1 0 0 0 3 2 3 3 3 0 2 0 1 2 1 2 1 3 0 2 2 2
 0 1 1 2 1 2 3 2 0 2 0 3 2 3 0 0 0 2 2 3 1 3 2 1 2 2 3 0 0 2 1 0 0 0 1 1 1
 1 1 3 2 1 2 1 1 0 3 3 1 2 0 3 1 3 1 3 2 1 3 1 0 2 3 0 0 3 0 3 0 1 0 0 1 0
 1 1 2 2 1 0 2 2 2 2 3 0 2 3 0 1 0 0 3 1 3 2 3 0 1 0 2 1 2 0 2 2 2 2 2 1 0
 3 1 0 0 1 3 2 2 0 2 1 3 3 0 1 2 2 3 1]
<class 'numpy.ndarray'>


In [14]:
#conditional probability outcome for [0, 1, 2, 3] of each row of test data
proba_list=clf.predict_proba(np.array(X_test.values))
proba_list

array([[0.00000000e+000, 0.00000000e+000, 1.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        1.00000000e+000],
       [1.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        1.00000000e+000],
       [1.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [1.00000000e+000, 0.00000000e+000, 0.00000000e+000,
      

In [15]:
clf.predict_proba([np.array(X_test.values)[0]])

array([[0., 0., 1., 0.]])

In [16]:
# score method in sklearn GaussianNB
accuracy=clf.score(X_test,y_test['Label'])
print('The Accuracy of algorithm is : ',accuracy*100, '%')

The Accuracy of algorithm is :  87.74509803921569 %


In [17]:
#variance of each feature per class
clf.sigma_

array([[1.54852622e-05, 1.54852622e-05, 1.54852622e-05, ...,
        1.54852622e-05, 1.54852622e-05, 1.54852622e-05],
       [1.54852622e-05, 1.54852622e-05, 1.54852622e-05, ...,
        1.54852622e-05, 1.54852622e-05, 1.54852622e-05],
       [1.54852622e-05, 1.54852622e-05, 1.54852622e-05, ...,
        1.54852622e-05, 1.54852622e-05, 1.54852622e-05],
       [1.54852622e-05, 1.54852622e-05, 1.54852622e-05, ...,
        1.54852622e-05, 1.54852622e-05, 1.54852622e-05]])

In [18]:
#mean of each feature per class
clf.theta_

array([[255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.]])