In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
train_df=pd.read_csv("training-images.csv",header=None)
train_df.rename(columns={ train_df.columns[784]: "Label" }, inplace = True)
train_df

0    1    2    3    4    5    6    7    8    9  ...  775  776  777  \
0    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
1    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
2    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
3    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
4    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
445  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
446  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
447  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
448  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
449  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   

     778  779  780  781  782  783  Label  
0    255  255  255  255  255  255      0  
1    255  255  255  255  255  255      0  
2    255  255  255  255  255  255      0  
3    255  255  255  255  255  255      0  
4    255  255  255  255  255  255      0  
..   ...  ...  ...  ...  ...  ...    ...  
445  255  255  255  255  255  255      3  
446  255  255  255  255  255  255      3  
447  255  255  255  255  255  255      3  
448  255  255  255  255  255  255      3  
449  255  255  255  255  255  255      3  

[450 rows x 785 columns]

In [2]:
test_df=pd.read_csv("test-images.csv",header=None)
test_df.rename(columns={ test_df.columns[784]: "Label" }, inplace = True)
test_df

0    1    2    3    4    5    6    7    8    9  ...  775  776  777  \
0    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
1    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
2    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
3    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
4    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
199  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
200  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
201  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
202  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
203  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   

     778  779  780  781  782  783  Label  
0    255  255  255  255  255  255      0  
1    255  255  255  255  255  255      0  
2    255  255  255  255  255  255      0  
3    255  255  255  255  255  255      0  
4    255  255  255  255  255  255      0  
..   ...  ...  ...  ...  ...  ...    ...  
199  255  255  255  255  255  255      3  
200  255  255  255  255  255  255      3  
201  255  255  255  255  255  255      3  
202  255  255  255  255  255  255      3  
203  255  255  255  255  255  255      3  

[204 rows x 785 columns]

In [3]:
comb_df=pd.concat([train_df, test_df], axis=0, ignore_index=True)
comb_df

0    1    2    3    4    5    6    7    8    9  ...  775  776  777  \
0    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
1    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
2    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
3    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
4    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
649  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
650  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
651  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
652  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
653  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   

     778  779  780  781  782  783  Label  
0    255  255  255  255  255  255      0  
1    255  255  255  255  255  255      0  
2    255  255  255  255  255  255      0  
3    255  255  255  255  255  255      0  
4    255  255  255  255  255  255      0  
..   ...  ...  ...  ...  ...  ...    ...  
649  255  255  255  255  255  255      3  
650  255  255  255  255  255  255      3  
651  255  255  255  255  255  255      3  
652  255  255  255  255  255  255      3  
653  255  255  255  255  255  255      3  

[654 rows x 785 columns]

In [4]:
from sklearn.cluster import KMeans
import numpy as np
X = comb_df.iloc[:,:-1]
kmeans = KMeans(n_clusters=4, random_state=5).fit(X)

In [5]:
kmeans.labels_

array([0, 1, 3, 3, 0, 1, 3, 3, 3, 0, 1, 0, 3, 0, 1, 3, 3, 3, 3, 3, 3, 3,
       3, 0, 1, 0, 3, 3, 0, 0, 3, 3, 1, 3, 3, 3, 0, 3, 0, 3, 3, 3, 1, 1,
       3, 3, 0, 3, 0, 0, 3, 1, 1, 1, 0, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 3,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 2, 1, 2, 2,
       1, 2, 1, 2, 2, 1, 2, 1, 1, 3, 1, 2, 1, 1, 2, 1, 3, 1, 1, 1, 2, 1,
       2, 1, 3, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1,
       1, 1, 1, 1, 1, 3, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 3, 2, 3, 2,
       1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1,
       2, 1, 2, 1, 2, 1, 2, 2, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 3, 1, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 1, 3, 3, 3,

In [6]:
temp_df=comb_df
temp_df["Cluster"]=kmeans.labels_
temp_df

0    1    2    3    4    5    6    7    8    9  ...  776  777  778  \
0    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
1    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
2    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
3    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
4    255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
649  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
650  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
651  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
652  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   
653  255  255  255  255  255  255  255  255  255  255  ...  255  255  255   

     779  780  781  782  783  Label  Cluster  
0    255  255  255  255  255      0        0  
1    255  255  255  255  255      0        1  
2    255  255  255  255  255      0        3  
3    255  255  255  255  255      0        3  
4    255  255  255  255  255      0        0  
..   ...  ...  ...  ...  ...    ...      ...  
649  255  255  255  255  255      3        3  
650  255  255  255  255  255      3        0  
651  255  255  255  255  255      3        3  
652  255  255  255  255  255      3        3  
653  255  255  255  255  255      3        3  

[654 rows x 786 columns]

In [7]:
kmeans.predict([X.iloc[0,:]]) #predicting for first row

array([0])

In [8]:
#final cluster centers after algorithm is completed
kmeans.cluster_centers_

array([[255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.],
       [255., 255., 255., ..., 255., 255., 255.]])

In [9]:
#Sum of squared distances of samples to their closest final cluster center
kmeans.inertia_ 

1792013103.5105875